spring:
  application:
    name: ringout

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ringout?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:ringringring}
    password: ${DB_PASSWORD:ringringring}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  packages-to-scan: com.ringout.api

app:
  swagger:
    local-url: ${SWAGGER_LOCAL_URL:http://localhost:8080}
    production-url: ${SWAGGER_PRODUCTION_URL:}
